name: Graph-SocialMap
version: 0.07
abstract: Easy way to create social map.
author: Kang-min Liu (gugod@gugod.org)
license: perl
distribution_type: module
requires:
  Spiffy: 0.19
  Graph: 0
  Graph::Writer::GraphViz: 0.03
no_index:
  directory:
    - inc
generated_by: Module::Install version 0.35
